"""autogenerated by genpy from subsomption/Channel.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Channel(genpy.Message):
  _md5sum = "8a78b9051527ab8b87f5963e4ef4b49d"
  _type = "subsomption/Channel"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool activated
float32 speed_left
float32 speed_right

"""
  __slots__ = ['activated','speed_left','speed_right']
  _slot_types = ['bool','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       activated,speed_left,speed_right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Channel, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.activated is None:
        self.activated = False
      if self.speed_left is None:
        self.speed_left = 0.
      if self.speed_right is None:
        self.speed_right = 0.
    else:
      self.activated = False
      self.speed_left = 0.
      self.speed_right = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2f.pack(_x.activated, _x.speed_left, _x.speed_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.activated, _x.speed_left, _x.speed_right,) = _struct_B2f.unpack(str[start:end])
      self.activated = bool(self.activated)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2f.pack(_x.activated, _x.speed_left, _x.speed_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.activated, _x.speed_left, _x.speed_right,) = _struct_B2f.unpack(str[start:end])
      self.activated = bool(self.activated)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B2f = struct.Struct("<B2f")
