(cl:defpackage fastsim-srv
  (:use )
  (:export
   "TELEPORT"
   "<TELEPORT-REQUEST>"
   "TELEPORT-REQUEST"
   "<TELEPORT-RESPONSE>"
   "TELEPORT-RESPONSE"
   "UPDATEDISPLAY"
   "<UPDATEDISPLAY-REQUEST>"
   "UPDATEDISPLAY-REQUEST"
   "<UPDATEDISPLAY-RESPONSE>"
   "UPDATEDISPLAY-RESPONSE"
  ))

