/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/catkin_ws/src/subsomption/msg/Channel.msg
 *
 */


#ifndef SUBSOMPTION_MESSAGE_CHANNEL_H
#define SUBSOMPTION_MESSAGE_CHANNEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subsomption
{
template <class ContainerAllocator>
struct Channel_
{
  typedef Channel_<ContainerAllocator> Type;

  Channel_()
    : activated(false)
    , speed_left(0.0)
    , speed_right(0.0)  {
    }
  Channel_(const ContainerAllocator& _alloc)
    : activated(false)
    , speed_left(0.0)
    , speed_right(0.0)  {
    }



   typedef uint8_t _activated_type;
  _activated_type activated;

   typedef float _speed_left_type;
  _speed_left_type speed_left;

   typedef float _speed_right_type;
  _speed_right_type speed_right;




  typedef boost::shared_ptr< ::subsomption::Channel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subsomption::Channel_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Channel_

typedef ::subsomption::Channel_<std::allocator<void> > Channel;

typedef boost::shared_ptr< ::subsomption::Channel > ChannelPtr;
typedef boost::shared_ptr< ::subsomption::Channel const> ChannelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subsomption::Channel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subsomption::Channel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace subsomption

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'subsomption': ['/home/viki/catkin_ws/src/subsomption/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::subsomption::Channel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subsomption::Channel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subsomption::Channel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subsomption::Channel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subsomption::Channel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subsomption::Channel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subsomption::Channel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a78b9051527ab8b87f5963e4ef4b49d";
  }

  static const char* value(const ::subsomption::Channel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a78b9051527ab8bULL;
  static const uint64_t static_value2 = 0x87f5963e4ef4b49dULL;
};

template<class ContainerAllocator>
struct DataType< ::subsomption::Channel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subsomption/Channel";
  }

  static const char* value(const ::subsomption::Channel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subsomption::Channel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool activated\n\
float32 speed_left\n\
float32 speed_right\n\
";
  }

  static const char* value(const ::subsomption::Channel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subsomption::Channel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activated);
      stream.next(m.speed_left);
      stream.next(m.speed_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Channel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subsomption::Channel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subsomption::Channel_<ContainerAllocator>& v)
  {
    s << indent << "activated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activated);
    s << indent << "speed_left: ";
    Printer<float>::stream(s, indent + "  ", v.speed_left);
    s << indent << "speed_right: ";
    Printer<float>::stream(s, indent + "  ", v.speed_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBSOMPTION_MESSAGE_CHANNEL_H
